### ISSUE TITLE
Moving core to Typescript

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/rfcs#1]
## Brief history 
[Typescript](https://www.typescriptlang.org/) is a superset of Javascript but improves the overall quality of the entire codebase in many ways.

## What problem does it solve?
1. Strict typing does help in mitigating some initial level bugs.
2. Typescript lovers can enjoy Adonis more, since their will be type-definitions for everything.
3. The biggest win is automatic API documentation using [typedoc](http://typedoc.org/). Writing API docs by hand(what we do now), is tough and harder to maintain. However, typedoc solves this for us.

## Proposal
Me (Harminder Virk), will take one piece at a time and will move it to Typescript. Since this change will become part of 5.0, I can take the leverage to code new features in Typescript and migrate the old codebase at the same time.

## Are you willing to work on it?
YES, YES, YES

**Comment by assertchris** [comment]
How will this change the experience of someone working in the framework, who doesn't want to use TS? Do I need to change my workflow or install additional tooling or serve the app any differently?

**Comment by thetutlage** [comment]
Nothing changes for the end user. I don’t want to enforce Typescript or any other compiled language to the end user.

The typescript is just for the core

**Comment by DCzajkowski** [comment]
It should have no effect for non-typescript users, as code still will be compiled to pure javascript.

**Comment by ammezie** [comment]
Will this be taking the approach of Angular? With options to either use Typescript or JavaScript?

**Comment by DCzajkowski** [comment]
I don't know the Angular case, but here it won't change anything for the end user. It's Node-based, all of the files will be compiled to native JS. So when you use it you won't see a difference, but Typescript-using folks will have type-safety built-in. :)

**Comment by niallobrien** [comment]
Will this affect startup time or as devs, will we be using the pre-compiled output?

**Comment by DCzajkowski** [comment]
As far as I know there is no way to run typescript without compiling it first, so there would be no changes to startup times.
If you are going to use Typescript there would be compilation time involved, but that takes place only once.

**Comment by thetutlage** [comment]
Lemme clear some doubts. 

1. Adonis core will make use of Typescript for benefits shared above. (For me the biggest one is the typedoc).
2. All code will be compiled to Javascript and only JS files are published on npm.
3. Your applications can continue using Javascript, **with no additional dependencies on runtime compilation**.

**Comment by DCzajkowski** [comment]
If you are going to put only js files to npm, how are the type definitions going to be available for users? Is TypeScript gonna create some typedef files?

**Comment by thetutlage** [comment]
It will be the `dist` folder generated by Typescript. So type definitions will be included. I was trying to say that `source .ts` files will not be published.

**Comment by DCzajkowski** [comment]
Ok, makes sense :)

**Comment by shirshak55** [comment]
nice :) Typescript is future of JS

**Comment by borie88** [comment]
Already starting to see some benefits with auto-completion in VS Code. This is great!

**Comment by SAGV** [comment]
Would there be any official docs on "how-to" use adonis with typescript? I'm especially interested in some guide on how to properly compile code for production and the final project structure with typescript

**Comment by RomainLanz** [comment]
Hey @SAGV! 👋 

Yes, there will be!

**Comment by SAGV** [comment]
Hi @RomainLanz,
This is awesome! Is there any update or ETA on the official typescript support?
(I'm not rushing, just curious)

**Comment by mtamadon** [comment]
Hi ,
How can I create a typescript boilerplate?
Will you provide that ?
Me and some other folks may want to use TS for the main app too.

**Comment by RomainLanz** [comment]
Hey @mtamadon! 👋 

Everything will be provided and explained, we do not help people installing V5 at the moment because it's not ready yet.

**Comment by aat2703** [comment]
How far is the progress on v5? Really looking forward to this... We're currently using Sequelize which is lacking so many features...

**Comment by RomainLanz** [comment]
Close to release. 👀

**Comment by aat2703** [comment]
Okay, i'll be waiting for the release before testing it out. Typescript is a must for us... 
Do you have en ETA?

**Comment by aat2703** [comment]
guys? 😆
