### ISSUE TITLE
Abandon TSLint; Switch to ESLint

### ISSUE THREAD

**Issue by lffg** [adonisjs/rfcs#17]
## Brief history 

Currently, I see that many of the new AdonisJs 5.x repositories are using TSLint, such as [create-adonis-app](https://github.com/AdonisCommunity/create-adonis-ts-app). I think that as TSLint is in a deprecation process, we should stop using it while the new Adonis version is not ready, so the transition will be smoother.

For more details about TSLint's deprecation process:
https://github.com/palantir/tslint/issues/4534

## What problem does it solve?

This change will make the inevitable transition from TSLint to ESLint much simpler. As soon as we switch, the better it will be for all of us. ;)

## Proposal

Switch TSLint to ESLint in the new AdonisJs repositories (and all the v5 packages and such).

## Relevant links

https://github.com/palantir/tslint/issues/4534

**Comment by thetutlage** [comment]
Yeah, seems like this is the package they recommend https://github.com/typescript-eslint/typescript-eslint/blob/master/README.md

Mind sharing a PR, that works with the current set of rules?

**Comment by lffg** [comment]
Yes! Maybe we can even create an `eslint-config-adonisjs`! What do you think?

I have one, called [eslint-config-lffg](https://github.com/lffg/eslint-config-lffg), that works with both JavaScript and TypeScript.

**Comment by thetutlage** [comment]
Yup, but the concern is to make it seamlessly work with Typescript. If you can share a config, which can replace the current tslint setup, then we can go ahead and use that as a preset. What you think?

**Comment by lffg** [comment]
Hello! I am sorry for the delay in answering...

---

I've recently updated [my ESLint configuration](https://github.com/lffg/eslint-config-lffg), so it does not depend on `eslint-config-react-app` anymore, which was causing a lot of compatibility issues.

My configuration is very strict about my code style, but it works perfectly with both JavaScript and TypeScript. It also uses Prettier to format the code (`.js`, `.jsx`, `.ts`, `.tsx` files).

If you want, we can use [it](https://github.com/lffg/eslint-config-lffg/blob/master/eslint-config-lffg.js) as a base to create a new ESLint configuration for AdonisJs (something like `eslint-config-adonis`). :)

But I also think that the users must have the ability to edit the default [adonis] configuration. Create React App, for example, does not do that and I think that this is a little bit prejudicial.

---

Related: https://www.npmjs.com/package/tslint-to-eslint-config
