### ISSUE TITLE
[Command] Schema update for Adonis

### ISSUE THREAD

**Issue by Hakamate** [adonisjs/rfcs#30]
## Brief history 
I'm not sure if Adonis offers this feature, because I can't find it. But the idea is to create a command to automaticaly check differences between database schema and Adonis models, to update the database structure.

That can be usefull during development.

## What problem does it solve?
This feature won't solve any real issues, but it can help users saving time.

## Proposal
N/A : Currently I don't have real ideas about how to do it.

## Relevant links
Symfony example : https://symfony.com/doc/3.3/doctrine.html#creating-the-database-tables-schema

## Are you willing to work on it?
Currently, I'm not sure to have sufficent time to work on it, but I can follow the development and maybe cheking a way to introduce it.

**Comment by thetutlage** [comment]
Again the same thing. We know that many things can be done, but they all require research and the actual work. One liner RFCs aren't going to help anyone
