### ISSUE TITLE
[Command] Make entity

### ISSUE THREAD

**Issue by Hakamate** [adonisjs/rfcs#31]
## Brief history 
Create a command to guide the user in creating a new entity, by doing a step by step questioning to know exactly the basic entity structure.

## What problem does it solve?
This feature won't solve any real issues, but it can help users saving time.
And help new developer to better understand things, especially in "how to make relationship".

## Proposal
N/A : Currently I don't have real ideas about how to do it.

## Relevant links
 - Symfony example (Make entity) : https://symfony.com/doc/current/doctrine.html#creating-an-entity-class
 - Symfony example (Mapping relationship) : https://symfony.com/doc/current/doctrine/associations.html#mapping-the-manytoone-relationship

## Are you willing to work on it?
Currently, I'm not sure to have sufficent time to work on it, but I can follow the development and maybe cheking a way to introduce it.

**Comment by thetutlage** [comment]
The RFC seems like trying to assign some work to others. Including the research and the actual implementation.

I will close it for now. Feel free to open it up in the future, when you think, you have time to work on it.

**Comment by Hakamate** [comment]
Ok no problem, but where can we suggest you some features ?

**Comment by thetutlage** [comment]
@Hakamate I believe you can create a discussion thread under ideas https://github.com/adonisjs/core/discussions
