### ISSUE TITLE
Treat `null` as a value in Validator.

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/rfcs#35]
The RFC tries to handle the use case of validating and returning `null` values through the validation pipeline. 

Up until now, the validator treats `null` no different than an `undefined` value. However, there are use cases where `null` needs a special treat. 

## Use case

Let's say you have a profile update form on your website and the **Country** field is optional. Initially, when the user created the account, they selected a country, and now they want to remove it, as they are not interested in disclosing their country anymore.

During the form submission, they empty the value for the **Country** field. The backend receives the value as `null`. (Actually, HTML forms submit empty fields as an empty string, but later in this doc, I will explain how you can convert it to `null` ).

In your update profile validator, you have marked the country as optional.

```ts
{
  country: schema.string.optional()
}
```

Post validation, the validated object will not have country property on it—Coz, the validator treats `null` and `undefined` as same.

> Side note: AdonisJS validator only returns the validated data from the `request.validate` call. All other values are removed.

With the final validated object, you run a SQL update query. However, the country in the database is never updated to `null` because the update payload does not have the country property in the first place.

You are stuck in a mode where the user cannot reset the value of a form field. There are ways to work around it, but that needs manual `if/else` clauses.

## Solution

The solution is very straightforward. We have to treat `null` as a value (which it is) and not undefined.

Once we do that, the validation output object will have the property and its value set to `null`.

### Use case 1: Value is `undefined`

- The required validation rule will make the validation cycle fail and abort.

### Use case 2: Value is `undefined` and marked as `optional`

- The required validation will not run
- We will skip all other validation rules as well since there is no value to validate
- The validation output does not contain the property.

### Use case 3: Value is `null`

Same as Use-case 1. The required validation rule will make the validation cycle fail.

### Use case 4: Value is `null` and marked as `optional`

Same as Use-case 2. By marking a field as optional, we assume that you want to ignore both `null` and `undefined` values.

### Use case 5: Value is `null` and marked as `allowNull`.

This use case will require us to introduce a new method to the validator schema.

```ts
{
  country: schema.string().allowNull(),
}
```

Here you expect the `country` to either have a value or be set to `null`. Also, the static types will represent the value as `string | null`. 

If the user provides a null value, then we will:

- Skip all the validation rules, as there is no value to validate.
- But return the property in the validated object as `null`

If you issue the same update SQL query, the database will set the `country` to `null`.

## Converting empty string to null

Empty strings are notorious values, which are not explicitly set by a user when submitting a form. They are set by the browser when the field value is empty.

Converting them to `null` ensures that you have a consistent experience when persisting the value in a database.

In v4, we have a middleware to convert empty strings to null. We will be adding that back in v5. Also, [Laravel](https://laravel.com/api/6.x/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.html), [Symfony](https://symfony.com/doc/current/reference/forms/types/text.html#empty-data) and Rails has [nilify blanks](https://github.com/rubiety/nilify_blanks) Gem.

**Comment by thejullius** [comment]
@thetutlage will this functionality still be implemented?
If so, where can I track progress?

**Comment by thetutlage** [comment]
Yes it will be. We have changed the RFC process and no longer explain them as issues and instead do PR's. I will get back on this.
