### ISSUE TITLE
Remove `make:view` when creating API-only application

### ISSUE THREAD

**Issue by bram-pkg** [adonisjs/rfcs#39]
I think the title is quite self-explanatory, this would help clean up the `ace` command line utility.

**Comment by thetutlage** [comment]
As the readme says, this is not how RFCs should be written

<img width="878" alt="Screen Shot 2021-06-09 at 8 55 10 AM" src="https://user-images.githubusercontent.com/1706381/121288127-7bda0200-c900-11eb-8ee9-97f45398e10a.png">
