### ISSUE TITLE
Guidance for front-end dev

### ISSUE THREAD

**Issue by assertchris** [adonisjs/rfcs#6]
## Brief history 
AdonisJS seems very back-end focussed (which isn't a bad thing IMHO). It obviously does support _any_ kind of front-end setup, but it suggest none. There's no bundled build-chain or suggested folder structure for front-end asset files. There's no documentation for how to set these up or how to integrate file watchers. Every third-party screencast suggests their own approach...

## What problem does it solve?
It can be daunting for folks not typically in the front-end space to consider adding any front-end structure to an AdonisJS app. Adding a tiny bit of structure would make it easier to know how/where to start, and could even cater for small-to-medium sized front-end setups without any custom configuration (when using something like ParcelJS as the provider).

## Proposal
I propose we add more folders to `resources`, complimentary structure to `public` (and `.gitignore`), a default ParcelJS bundle configuration, and some documentation. I'm not suggesting anything as radical as "picking a favourite" framework or approach to front-end dev. Just something that acts as an entry-point, and hooks up things like CSRF for Ajax would be immensely useful.

## Relevant links
https://parceljs.org
https://github.com/laravel/laravel/blob/0d5c1c81ff6faafbd8cc995aa3d0cd1b155df4c3/resources/assets/js/bootstrap.js#L23-L39
https://twitter.com/assertchris/status/1026770099552829440

## Are you willing to work on it?
Yes

**Comment by ammezie** [comment]
I'm all in support with this.

**Comment by Nefiron** [comment]
Bringing Parcel or any bundler with it for easy integration would surely benefit the ecosystem I would say. I am all in favor of this!

**Comment by thetutlage** [comment]
> Laravel mix is also nice, and should work with Adonis too.

Yes, I am in with this. Parcel seems great, but I believe, their first approach is to support SPA's. If I am not wrong, Parcel starts with a `.html` file and then auto discover `scripts` and `styles` and bundles them.

Whereas, with Adonis, we need more of a build pipeline. Where assets inside dedicated directories are compiled and dropped inside the `public` folder. 

Finally, @assertchris it will be nice, if you can share some implementation details, along with the end-user API and configuration.

Should I assign this to you? We can have this as a separate repo inside the core and you as the lead maintainer.

**Comment by assertchris** [comment]
Sure, but i think the best place for it to live is inside the fullstack-app repo. 

Parcel does initially work from a single entry-point, but it can be configured as to which entry-point to use: https://github.com/atfotc/audio-extractor/blob/master/bundle.js

Mix is also a good option, since it has better built-in support for file versioning...

**Comment by RomainLanz** [comment]
I have started time ago a bundler using Parcel for Adonis.

https://github.com/romainlanz/adonis-bundler

There's some issue with using Parcel like that, caching doesn't work well, we cannot have manifest without hacking the code, hooking inside may be difficult (like copying files, processing images, etc.).

**Comment by assertchris** [comment]
@thetutlage please assign to me. I'll get a mix impl up.

**Comment by shirshak55** [comment]
I also like laravel mix but it seems sometime too bulky requiring too many dependencies so usually I go with my own webpack stuff :(

**Comment by assertchris** [comment]
@shirshak55 I think the idea here is to provide guidance for folks who don't know how to set their own webpack stuff up. More dependencies isn't a bad thing for these folks.

**Comment by thetutlage** [comment]
Yeah I agree with @assertchris here. People comfortable with Webpack, feel free to ignore any assets pipeline created for AdonisJs.

Whereas, it's useful for people:

1. Finding their way around and don't want to spend much time configuring webpack.
2. Creating blog posts to teach others.
3. Also webpack dependencies are mainly for development and you just ship the final `Js/Css` to your servers.

@assertchris assigned to you

**Comment by K3TH3R** [comment]
@assertchris I have a fairly robust webpack config/setup already built for my Adonis application... there's some custom stuff that would take a while to rip out, but I could send you the major pieces to give you a good starting point/reference. Stuff I already have figured out:
- HMR + auto-refresh on template changes
- sass/js compilation + image minification
- asset hashing for built production files

**Comment by K3TH3R** [comment]
@assertchris grabbed my Webpack stuff, ripped out the customizations and put it into [a fresh Adonis project](https://gitlab.com/K3TH3R/adonis-webpack) if you want a starting point

**Comment by thetutlage** [comment]
@assertchris Are you still up to work on the official assets pipeline. I am personally okay with Laravel mix and Parcel both. However, we can discuss more if required.

**Comment by RomainLanz** [comment]
I believe we don't need to build this.
We should let the final user decide on which assets pipeline they want to choose.

It could be `Symfony Encore`, `Laravel Mix`, `Parcel`, `Custom Webpack config`, whatever...

What could be done is getting one of those and building docs/recipes around it.

**Comment by thetutlage** [comment]
I am happy with either approach. If we go with docs, then we should write for couple of them inside recipes. But let's see what everyone wants

**Comment by shirshak55** [comment]
Yes laravel mix will be too opinionated . I love laravel mix but still let end user decide :)

**Comment by assertchris** [comment]
Ok,, let's go with docs instead.

**Comment by jhon-andrew** [comment]
Ping.

**Comment by drmnk** [comment]
Hello, sorry for late, but maybe we should not include Parcel\Webpack\etc right in the codebase and not only add recipes in documentation, but provide some scaffolding with Ace?

**Comment by RomainLanz** [comment]
We will never provide Parcel / Webpack / Others X directly in our codebase. As you state, we will provide recipes and guidance about how to use them with our framework.

**Comment by seccomiro** [comment]
Is there a repo for this WIP?
I couldn't find it.
