### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by mourad-ghafiri** [adonisjs/rfcs#8]
## Brief history 
MongoDB is the leading document NoSQL databases and it is used by many big companies and startups so there is no logical reason to ignore it.

## What problem does it solve?
Using adonisjs Lucid standard module to deal with Mongodb as well instead of using thirdparty non maintained packages or the mongo native driver.

## Relevant links
a great example of lucid overriding to support Mongodb
https://github.com/duyluonglc/lucid-mongo

**Comment by thetutlage** [comment]
Please don't use RFC's as a way to request features. Recommend you to read the [README](https://github.com/adonisjs/rfcs) first.

Also, you have to share a proper proposal on how it should be implemented. Right now your RFC is just a feature request, asking us to do all the research work and then implement it.
